title: Rust Server Manager Wiki
logo: https://www.google.com/s2/favicons?domain=rustservermanager.com
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
